### ISSUE TITLE
Install failed : 'No such file or directory'

### ISSUE THREAD

**Issue by javiergodoy** [djacobs7/remembr#1]
> remembr::remembr_install()
Registered S3 method overwritten by 'pryr':
  method      from
  print.bytes Rcpp
Error: .onLoad failed in loadNamespace() for 'remembr', details:
  call: gzfile(file, "rb")
  error: cannot open the connection
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file 'data/default_call_counts_hash_table.Rds', probable reason 'No such file or directory'

**Comment by djacobs7** [comment]
Thanks! Will patch!

**Comment by djacobs7** [comment]
Thank you for the bug report, it's very helpful!  I made a patch that should deal with this, and tested it locally.

If you quit R and then follow the install instructions again, it should fix itself.  

    devtools::install_github( "djacobs7/remembr"); library(remembr); install_remembr()

**Comment by javiergodoy** [comment]
It worked !  Thank you
